#!/bin/bash

# Make sure only one daemon exits
if [ -e "/tmp/chromemacs-daemon.pid" ]
then
    ps aux | grep chromemacs-daemon | grep `cat /tmp/chromemacs-daemon.pid` | awk '{print $2}' | xargs kill -9
fi
echo $$ > /tmp/chromemacs-daemon.pid

last_msg=""
msg=""

while [ 1 == 1 ]; do
    current_window_class=`xprop -id $(xdotool getwindowfocus) WM_CLASS`
    if [[ $current_window_class == *google-chrome* ]]
    then
        msg="chromemacs::start"
    else
        msg="chromemacs::stop"
    fi
    if [ "$msg" != "$last_msg" ]; then
        echo -e $msg
        dotxbindkeys send-message $msg
    fi
    last_msg=$msg
    sleep 0.5
done
